### ISSUE TITLE
delegates: typo

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#10]
https://ark.io/delegates

In the `Claiming Your Delegate` section, `you\ve` instead of `you've`.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
