### ISSUE TITLE
style: bottom margin only half way in content-wrapper

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#11]
e.g.

![image](https://user-images.githubusercontent.com/6547002/61108924-ec154a00-a483-11e9-94ef-cb0334a538bb.png)

The after pseudo-element (=> bottom margin) of the `intro-tools-content-wrapper--left` and `intro-tools-content-wrapper--right` classes doesn't extend over the whole width.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dated** [comment]
By looking at the css classes this appears to be by design 🤷‍♂

**Comment by ItsANameToo** [comment]
Do you mean the border that only fill 50%? 🤔

**Comment by dated** [comment]
Yea, I figured it's probably by design. Feel free to close.

**Comment by ItsANameToo** [comment]
Indeed :lel:

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
