### ISSUE TITLE
style: bottom-border of last table row

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#12]
The last table rows should not have a border (as is the case with all other tables on the Wallet and Explorer etc).

e.g. https://ark.io/projects

![image](https://user-images.githubusercontent.com/6547002/61109179-92f9e600-a484-11e9-8fa0-72d4ae920047.png)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
I assume you mean `border` instead of `margin` 🤔

**Comment by dated** [comment]
Yes, sorry, border.

**Comment by ItsANameToo** [comment]
fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
