### ISSUE TITLE
style: td cells have bigger horizontal padding than th cells

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#13]
The table header cells have a smaller horizontal padding than the cells in the table body, which makes the whole table feel off and unbalanced.

Can be closed if this is by design of course.

![image](https://user-images.githubusercontent.com/6547002/61109420-27644880-a485-11e9-9787-27e075eab79f.png)

![image](https://user-images.githubusercontent.com/6547002/61109447-30edb080-a485-11e9-903c-3bf83e41c9a6.png)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
It's by design, but I'll run it by Oleg to be sure

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
