### ISSUE TITLE
github: vertical alignment of repository details

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#14]
![image](https://user-images.githubusercontent.com/6547002/61109613-9cd01900-a485-11e9-9dd2-9da5ad091781.png)

The repository details (PRs, issues, ...) should be vertically aligned.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.

**Comment by dated** [comment]
What i meant to say here is that the details are vertically aligned in the footer of the repository placeholder, while there is an offset in the regular panels :thinking:

**Comment by ghost** [comment]
This issue has now been re-opened. If applicable please provide additional information as requested by one of the reviewers.

**Comment by ItsANameToo** [comment]
now actually fixed :trollface:

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.

**Comment by dated** [comment]
:noah:
