### ISSUE TITLE
github: `More repositories` panel background color and anchor

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#15]
Two minor issues with this panel:

1) Hovering adds a white line underneath it

![image](https://user-images.githubusercontent.com/6547002/61109738-e882c280-a485-11e9-95dd-5ab62622952f.png)

2) Clicking on `More repositories` (not the panel itself, which works fine) which points to https://ark.io/github# triggers are scroll event

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.

**Comment by dated** [comment]
Has this been pushed to production? The anchor is fixed, the white border is still visible 🤔

**Comment by ItsANameToo** [comment]
Yes, seems indeed that the white border is still visible so I'll take another look at that 🤔

**Comment by ghost** [comment]
This issue has now been re-opened. If applicable please provide additional information as requested by one of the reviewers.

**Comment by ItsANameToo** [comment]
fixed

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
