### ISSUE TITLE
aips: table styling

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#16]
The styling of the AIP table on https://ark.io/aips does not align well with the rest of the tables and overall design.

Highjacking for a minor nitpick: it should be `Submit your AIP` instead of `Open your AIP`.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
Will run it past Oleg

**Comment by ItsANameToo** [comment]
fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
