### ISSUE TITLE
tabs: hover pointer and anchor

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#17]
The pointer arrow is displayed when hovering over the div containing the anchor, giving the impression that the element is clickable - which is not the case when the mouse is placed on the padding instead of the anchor tag directly.

Solution: add padding to anchor instead of div.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
