### ISSUE TITLE
bounties: top earners table does show username instead of name

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#18]
![image](https://user-images.githubusercontent.com/6547002/61330766-a4dede80-a820-11e9-906e-7e7531051194.png)

The mobile `Top Earners` does show the developer's username instead of the name in the name column.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
humble brag :trollface:

**Comment by ItsANameToo** [comment]
Fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
