### ISSUE TITLE
footer: misalignment of icons and links

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#19]
![image](https://user-images.githubusercontent.com/6547002/61331347-15d2c600-a822-11e9-853f-6d90048d1a67.png)

The icons and links are not evenly aligned.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
Fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
