### ISSUE TITLE
home: panel borders and background color

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#20]
Each panel has a border on all sides, causing the line in the middle to be 2px wide. Can be solved by simulating border-collapse by removing the left/right border on one of the elements (as is done with the `About ARK` panels).

Moving the mouse from one panel to the other causes the white background to shine through the newly hovered panel for the duration of the animation. Can be solved by adding a background color to the panels instead of using transparent (the same applies to the `About ARK` panels).

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
Fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
