### ISSUE TITLE
Stats divider off-center

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#23]
![image](https://user-images.githubusercontent.com/6547002/62213164-9bb64b80-b3a2-11e9-95e0-84330e60c20b.png)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
Fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
