### ISSUE TITLE
feature request: include link to GitHub bounty report

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#24]
It would be nice to have a link to the GitHub bounty reports on the leaderboard for previous months.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please review and correct it.

**Comment by ItsANameToo** [comment]
Nice description

**Comment by dated** [comment]
:colbert:

**Comment by ItsANameToo** [comment]
What's the reason you want to have the link? What kind of information are you missing on the page itself? 🤔

**Comment by dated** [comment]
The blog gives much more details about what kind of PRs have been done - the bounty page lists only the number of merged PRs.

An alternative, much more complicated solution, would be to add a modal which can be opened by clicking on the PR count which then lists the merged PRs. This approach would however would also allow to see which PRs were merged in the current month.

This is totally a personal nice-to-have, since I find myself searching for the bounty reports on the ark.io blog from time to time.

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
