### ISSUE TITLE
Old email icon in side menu

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#26]
The side menu features the old email icon:

![image](https://user-images.githubusercontent.com/6547002/63154844-cf83a900-c011-11e9-9688-f4ab1f17cb3d.png)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
Fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
