### ISSUE TITLE
user-hub: missing shadows on blue buttons

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#28]
The blue buttons on the user hub page are missing the shadows.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.

**Comment by ghost** [comment]
This issue has now been re-opened. If applicable please provide additional information as requested by one of the reviewers.

**Comment by ItsANameToo** [comment]
Awesome, didn't knew that stalebot now actually closes them @faustbrian :colbert:

**Comment by faustbrian** [comment]
🚒

**Comment by ItsANameToo** [comment]
Those buttons are different from the regular blue buttons (they have somewhat of a gradient in it and upon hovering that changes), so they intentionally don't have that shadow.

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
