### ISSUE TITLE
Incorrect github users on bounty page

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/ark.io-issues#3]
The bounty page reports incorrect users accounts for some of the bounties (e.g. https://github.com/paroxysmofhappiness and https://github.com/vuleticd) as their names collide with the actual users we want (paroxysm and vulet).

**Comment by ItsANameToo** [comment]
I assume it's due to their names being a substring of the ones that github returns 🤔

**Comment by faustbrian** [comment]
Was an issue with how GitHub returned data on listing contributors vs. retrieving a specific contributor.

Reindexed all data so should be fixed now.
