### ISSUE TITLE
Empty Leaderboard after switching back from Top Earners

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#31]
https://ark.io/bounties

On mobile: When switching between the Top Earners and Leaderboard tabs the Leaderboard table loses it's entries.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dated** [comment]
:colbert:

**Comment by ItsANameToo** [comment]
Poor you :colbert:

**Comment by ItsANameToo** [comment]
fixity fix

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.

**Comment by ItsANameToo** [comment]
fixy mcfixface? 🤔

**Comment by dated** [comment]
:danwhat:
