### ISSUE TITLE
Update exchanges

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/ark.io-issues#33]
- OKEx doesn't offer ARK/ETH anymore
 - Bitvavo is missing from ARK/EUR

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
@boldninja

**Comment by boldninja** [comment]
Thank you @j-a-m-l I have removed OKEx ARK/ETH and added Bitvavo exchange.

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
