### ISSUE TITLE
home: hovering over user/developer hub displacing elements

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#4]
Hovering over the User Hub and Developer Hub panels on the homepage slightly displaces adjacent elements and elements underneath the panels.

**Your Environment**

Chrome
Version 75.0.3770.100 (Official Build) (64-Bit)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
