### ISSUE TITLE
menu: missing margin between menu title and items

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#5]
![image](https://user-images.githubusercontent.com/6547002/61107909-43fe8180-a481-11e9-8a10-e70968046e68.png)

There should be a margin between the title and the first menu item (or bottom padding on the title) imho.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
