### ISSUE TITLE
wallet: add fixed width to intro slider

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#6]
![image](https://user-images.githubusercontent.com/6547002/61108069-afe0ea00-a481-11e9-83d2-0c4ef46281a5.png)

By adding a fixed width to the div between the arrows stops the arrow buttons to be displaced upon clicking.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
