### ISSUE TITLE
contact-form: missing styles on select

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#7]
![image](https://user-images.githubusercontent.com/6547002/61108283-35fd3080-a482-11e9-9525-515eb046a8b0.png)

The select element is missing custom styles.

**Your Environment**

Chrome
Version 75.0.3770.100 (Official Build) (64-Bit)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dated** [comment]
take your time fixy mcfixface :trollface:

**Comment by ItsANameToo** [comment]
well excuse me :colbert:

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
