### ISSUE TITLE
tabs: vertical alignment of tab selection

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#8]
Vertically aligning the tab titles with the main title looks more balanced imho.

![image](https://user-images.githubusercontent.com/6547002/61108544-d5222800-a482-11e9-9002-44a2c97ed42b.png)

vs

![image](https://user-images.githubusercontent.com/6547002/61108555-dce1cc80-a482-11e9-8104-a312ee9e8b80.png)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dated** [comment]
The https://ark.io/roadmap page shows the tabs "correctly".

**Comment by ItsANameToo** [comment]
fixed on develop

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
