### ISSUE TITLE
feature request: include ama logs in past events

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark.io-issues#9]
It would be nice to have a link to the logs of the respective past AMA in the details modal.

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
Sam will add a link to the event pointing to the log after the AMA has concluded

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
